### ISSUE TITLE
rustup not found during `rustup install ${MINIMUM_RUSTC_VERSION}`

### ISSUE THREAD

**Issue by woelfman** [brummer-simon/text_to_morse#5]
On Fedora 39, when rustup installs ${MINIMUM_RUSTC_VERSION} there is an error that rustup can not be found at ${RUSTUP_BIN_DIR}/rustup. I presume this has to do with the the environment variables that are set to override cargo and rustup.

I have solved this locally by adding a rustup installation step in the script to install to the expected location. Either this explicit install or a tweak to the environment variables is needed, at least on my system.

Here is the change I made:

```diff
diff --git a/scripts/common.sh b/scripts/common.sh
index da04655..2f23422 100644
--- a/scripts/common.sh
+++ b/scripts/common.sh
@@ -198,6 +198,11 @@ function setup_rust_tooling() {
     then
         mkdir -p "${RUSTUP_BIN_DIR}"
 
+        if [ ! -x "${RUSTUP_BIN_DIR}/rustup" ]
+        then
+            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
+        fi
+
         # Build required rust version and link tooling it to host bin location
         # shellcheck disable=SC2086 # Deliberate word splitting
         rustup install ${MINIMUM_RUSTC_VERSION}

```

**Comment by brummer-simon** [comment]
I haven't though of it because I installed rustup from my packet manager so it might be somewhere in the path. I will try it this way.

**Comment by brummer-simon** [comment]
@woelfman: Thanks for pointing out this issue. The next version applies your diff with some adjustments. I use wget because it is already a dependency of buildroot, I install it without a toolchain as the required ones are added later on anyway and rustup ends up in CARGO_BIN_DIR not RUST_BIN_DIR.
