### ISSUE TITLE
Failed build due to linker not found

### ISSUE THREAD

**Issue by senekor** [brummer-simon/text_to_morse#9]
The first build (`make build_env build_module logi`) fails for me now with the following error:

```
Linux config does not exist. Create it.
scripts/Kconfig.include:40: linker 'ld.lld' not found
make[4]: *** [/home/remo/repos/text_to_morse/env/linux/scripts/kconfig/Makefile:94: qemu_defconfig] Error 1
make[3]: *** [/home/remo/repos/text_to_morse/env/linux/Makefile:693: qemu_defconfig] Error 2
make[2]: *** [Makefile:226: __sub-make] Error 2
make[1]: *** [Makefile:51: build_linux] Error 2
make: *** [Makefile:45: build_env] Error 2
```

I don't have any experience with buildroot, so no idea what's going on.
`ld` is of course installed on my system and the following didn't fix the problem either:
```
LD=/usr/bin/ld make build_env build_module logi
```

**Comment by senekor** [comment]
Fixed it:

```
sudo dnf install lld
```

I coulnd't find `lld` anywhere in the documented dependencies though (this repo incl. links to builldroot and linux development).

**Comment by brummer-simon** [comment]
Thanks for pointing this out. I'll add it to the dependencies with the next merged.
